In [1]:
import jax 
import jax.numpy as jnp

In [3]:
# Set the random seed
key = jax.random.PRNGKey(0)

# Generate a vector of 20 random numbers from a uniform distribution
random_vector = jax.random.uniform(key, shape=(21,))

print(random_vector)

[0.05943918 0.26881337 0.60546124 0.7813201  0.54375553 0.5628723
 0.6746079  0.7347511  0.9062828  0.00449073 0.20543814 0.03636956
 0.11710262 0.65541315 0.84022856 0.82869196 0.64946747 0.606181
 0.04686642 0.99509585 0.40941238]


In [5]:
random_vector=random_vector.reshape(7,-1)
random_vector

Array([[0.05943918, 0.26881337, 0.60546124],
       [0.7813201 , 0.54375553, 0.5628723 ],
       [0.6746079 , 0.7347511 , 0.9062828 ],
       [0.00449073, 0.20543814, 0.03636956],
       [0.11710262, 0.65541315, 0.84022856],
       [0.82869196, 0.64946747, 0.606181  ],
       [0.04686642, 0.99509585, 0.40941238]], dtype=float32)

In [6]:
import jax.numpy as jnp
import jax.lax as lax

# Creamos un arreglo de ejemplo
x = jnp.arange(30).reshape(3, 10)
print(x)

# Extraer desde la posición 0 a la 5 en la segunda dimensión
sliced = lax.slice(x, (0, 2), (3, 7))  # Cortamos de (0,2) a (3,7)
print(sliced)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
[[ 2  3  4  5  6]
 [12 13 14 15 16]
 [22 23 24 25 26]]
